[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "sphinx-lint"
description = "Check for stylistic and formal issues in .rst and .py files included in the documentation."
readme = "README.md"
license = {text = "PSF License"}
authors = [
    {name = "Georg Brandl", email = "georg@python.org"},
    {name = "Julien Palard", email = "julien@palard.fr"},
]
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Topic :: Documentation :: Sphinx",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: Python Software Foundation License",
    "Natural Language :: English",
    "Programming Language :: Python :: 3",
]
requires-python = ">= 3.7"
dependencies = [
    "regex",
    "polib",
    "tomli>=2; python_version < '3.11'",
]
dynamic = ["version"]


[project.urls]
repository = "https://github.com/sphinx-contrib/sphinx-lint"

[project.scripts]
sphinx-lint = "sphinxlint.__main__:main"

[tool.setuptools]
packages = ["sphinxlint"]
include-package-data = false
dynamic.version.attr = "sphinxlint.__version__"

[tool.black]

[tool.pylint.variables]
callbacks = ["check_"]
